apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: configs/argocd
    repoURL: https://github.com/vguttmann/k8s-homelab
    targetRevision: HEAD
