global:
  revisionHistoryLimit: 1
  additionalLabels:
    app: argo-cd

controller:
  resources:
    requests:
      cpu: 100m
      memory: 750M
#  metrics:
#    enabled: true
#    serviceMonitor:
#      enabled: true
dex:
  enabled: false

redis:
  enabled: true
  resources:
    requests:
      cpu: 15m
      memory: 30m


server:
  config:
    kustomize.buildOptions: --enable-helm


configs:
  repositories: {}
    private-repo:
      url: https://github.com/vguttmann/homelab-k8s
